#!/bin/sh

echo "=================================="

POSIXLY_CORRECT=yes
HELP=0
N=0

# --- Processing flags ---
while getopts :i:n o # netusim co dela dvojtecka na zacatku
do	case "$o" in
		i) FILE_ERE="$OPTARG";;
		n) N=1;;
		*) HELP=1;;
	esac
done


#echo "[DBG] FILE_ERE=$FILE_ERE"
#echo "[DBG] OPTIND=$OPTIND"
#echo "[DBG] #=$#"


# --- Processing target directory ---
ARGC=$#
if [ "$OPTIND" -eq "$ARGC" ]; then
	((OPTIND--))
	shift $OPTIND	
	DIR="$*"
else
	((OPTIND--))
	if [ "$OPTIND" -eq "$ARGC" ]; then
		DIR=$(pwd)
	else
		HELP=1
	fi
fi

# --- Returning help ---
if [ "$HELP" -eq 1 ]; then
	echo "NAPOVEDA"
	exit 0
fi

# --- Normalization (-n FLAG) ---
if [ "$N" -eq 1 ]; then
	if [ -t 1 ]; then
		N=$(tput cols) # Proc se to musi takhle?
		((N=$N-13))
	else
		N=67
	fi
fi

#echo "[DBG] DIR=$DIR"

#ND=$(find $DIR -type d | wc -l)
#NF=$(find $DIR -type f | wc -l) # Jsou to normalni soubory?
echo $N 

find $DIR -type f -not -regex "$FILE_ERE"  -exec du -b {} + | awk -v gmax="$N" '
{
	if($1 < 100)
		size[0]++;
	else if($1 < 1024)
		size[1]++;
	else if($1 < 10240)
		size[2]++;
	else if($1 < 102400)
		size[3]++;
	else if($1 < 1048576)
		size[4]++;
	else if($1 < 10485760)
		size[5]++;
	else if($1 < 104857600)
		size[6]++;
	else if($1 < 1073741824)
		size[7]++;
	else
		size[8]++;
}
END{
prefix[0] = "<100 B  ";
prefix[1] = "<1 KiB  ";
prefix[2] = "<10 KiB ";
prefix[3] = "<100 KiB";
prefix[4] = "<1 MiB  ";
prefix[5] = "<10 Mib ";
prefix[6] = "<100 Mib";
prefix[7] = "<1 GiB  ";
prefix[8] = ">= 1 GiB";

for (i = 0; i < 9; i++)
{
	if(gmax == 0 || size[i] < gmax)
		max = size[i];
	else
		max = gmax;

	printf "  %s: ",prefix[i];
	for (j = 0; j < max; j++)
	{
		printf "#";
	}
	printf "\n";
}

}'

echo "=====RESULT====="
echo "Root directory: $DIR"
echo "Directories: $ND"
echo "All files: $NF"
echo "File size histogram:"
echo "File type histogram:"
